---
title: "Postprocessing A2"
author: "Stefano Longo"
date: "11/18/2019"
output: html_document
---

```{r packages}
if(!require("remotes")){
  install.packages("remotes")
}

if(!require("krr")){
  remotes::install_github("TimothyKBook/krr")
}

if(!require("dplyr")){
  install.packages("dplyr")
}

if(!require("caret")){
  install.packages("caret")
}


library(krr)
library(dplyr)
library(caret)
```

```{r}
#read output and data
train_set<-read.csv("../data/train_set.csv")
test_set<-read.csv("../data/test_set.csv")
q <- read.csv("../output/A2_q_100.csv")
movie<-read.csv("../output/movie_indexes.csv")
r <- read.csv("../output/A2_r_100.csv")
```

```{r}
#data transformation and get input of krr
train_split<-split(train_set,train_set$userId)
q<-as.matrix(q[,-1])
q<-t(q)
movie<-movie[,-1]

new_q_split<-list()
for (k in 1:length(train_split)){
  new<-c()
for (i in 1:dim(train_split[[k]])[1]){
 new<-cbind(new,q[,which(movie==train_split[[k]]$movieId[i])])}
 new_q_split[[k]]<-new}

normal <- function(a){return(a/sqrt(sum(a^2)))}

q_trans<-t(apply(q,2,normal))

x_split<-list()
for (k in 1:length(train_split)){
  x_split[[k]]<-apply(new_q_split[[k]],2,normal)}

data_split<-list()
for (k in 1:length(train_split)){
  data_split[[k]]<-cbind(train_split[[k]]$rating,t(x_split[[k]]))}
```

```{r CV FUNCTION}
#write a function to do cross validation and tune parameter lambda in krr
cv.krr <- function(data, kfold, lam){
  
  set.seed(123)
  data.x <- as.matrix(data[,-1])
  data.y <- data[,1]
  n <- nrow(data.x)
  cv.id <- createFolds(1:n, k = kfold)
  cv.tuning <- c()
  for (j in cv.id){
    #Split Data in train and validation sets
    x.train.cv <- data.x[-j,]
    y.train.cv <- data.y[-j]
    x.validation.cv <- data.x[j,]
    y.validation.cv <- data.y[j]
    
    #Run Model
    mod.cv <- krr(x = x.train.cv,  y.train.cv, lambda = lam)
    #Estimate predictin of validation test
    pred.cv <- predict(mod.cv, x.validation.cv)
    
    #Calculate RMSE
    rmse.cv <- sqrt(mean((y.validation.cv - pred.cv)^2))
    cv.tuning <- cbind(cv.tuning, rmse.cv)
    cv.mean <- mean(cv.tuning)
    }
  return(cv.mean)
}
```

```{r TUNE LAMBDA}
#find a best lambda
lambdas <- c(0.45, 0.50, 0.55)
rmse_tune <- data.frame(lambdas=lambdas,rmse=rep(0,length(lambdas)))
for (i in 1:length(lambdas)){
  m <- lapply(data_split, cv.krr, 5, lambdas[i])
  rmse_tune[i,2] <-  sum(unlist(m))
}

best_lambda <- rmse_tune %>%
  filter(rmse == min(rmse))
best_lambda <- best_lambda$lambda
```


```{r}
#use tuned lambda to train 610 users model
train_model <- vector(mode="list",length=length(data_split))
for(i in 1:length(data_split)){
  train_model[[i]]<-krr(data_split[[i]][,-1],data_split[[i]][,1], best_lambda)}
#get prediction in a matrix with dimension 610*9724
pred_rating<-matrix(NA,nrow=length(data_split),ncol=dim(q)[2])
for (i in 1:length(data_split)){
  pred_rating[i,]<-predict(train_model[[i]],q_trans)}

```

```{r}
rating.a2 <- as.matrix(r)
rating.a2 <- rating.a2[,-1]
colnames(rating.a2)<-c(as.character(movie))
rownames(rating.a2)<-c(1:610)
colnames(pred_rating)<-c(as.character(movie))
rownames(pred_rating)<-c(1:610)
```

```{r}
#function to calculate mse
mea<-function(data,test){
  movies<-data$movieId
  users<-data$userId
  pred<-as.numeric(t(test[match(c(as.character(users)),rownames(test)),match(c(as.character(movies)),colnames(test))]))
  return(mean((data$rating-pred)^2))
}
```

```{r}
#get the best weight
weights <- seq(0,1,0.1)
rmse_train <- data.frame(weights=weights,rmse=rep(0,length(weights)))
rating.weighted<-list()
dim(train_set)[1]
for (i in 1:length(weights)){
  rating.weighted[[i]]<- rating.a2*(1-weights[i]) + pred_rating*weights[i]
  rating.weighted[[i]]<-as.matrix(rating.weighted[[i]])
  mean1<-mea(train_set[1:10000,],rating.weighted[[i]])
  mean2<-mea(train_set[10001:20000,],rating.weighted[[i]])
  mean3<-mea(train_set[20001:30000,],rating.weighted[[i]])
  mean4<-mea(train_set[30001:40000,],rating.weighted[[i]])
  mean5<-mea(train_set[40001:50000,],rating.weighted[[i]])
  mean6<-mea(train_set[50001:60000,],rating.weighted[[i]])
  mean7<-mea(train_set[60001:70000,],rating.weighted[[i]])
  mean8<-mea(train_set[70001:80000,],rating.weighted[[i]])
  mean9<-mea(train_set[80001:dim(train_set)[1],],rating.weighted[[i]])
  rmse_train[i,2]<-sqrt(((mean1+mean2+mean3+mean4+mean5+mean6+mean7+mean8)*10000+(dim(train_set)[1]-80000)*mean9)/dim(train_set)[1])
}
rmse_train
```

```{r}
#get test rmse
best_weight <- match(min(rmse_train$rmse), rmse_train$rmse)

mean11<-mea(test_set[1:10000,], rating.weighted[[best_weight]])
mean21<-mea(test_set[10001:20000,],rating.weighted[[best_weight]])
mean32<-mea(test_set[20001:dim(test_set)[1],],rating.weighted[[best_weight]])
rmse_test<-sqrt(((mean11+mean21)*10000+(dim(test_set)[1]-20000)*mean32)/dim(test_set)[1])
rmse_test
```

